Repository Just-Some-Bots/MusicBot, pull requests merged in 2019-08, with the labels that each got.

#1860 [Bugfix] Ignore extraction error from ytdl that is preventing bot from playing playlist with some bad entries
  musicbot/bot.py
Labels: a/backend, a/playback

#1896 Ignore other bots and inactive people in voice channel
  musicbot/bot.py
Labels: a/cmds, a/frontend, t/enhancement

#1935 Improvement guild nick and user id's in perm command
  musicbot/bot.py
Labels: a/cmds, a/frontend

#1922 Improvement add custom embed footer
  config/example_options.ini
  musicbot/bot.py
  musicbot/config.py
Labels: a/frontend, a/options, t/enhancement
