Repository Just-Some-Bots/MusicBot, pull requests merged in 2020-03, with the labels that each got.

#2008 Keyless Spotify
  config/example_options.ini
  musicbot/bot.py
  musicbot/spotify.py
Labels: a/options, t/enhancement

#1946 Fix for showing negative estimated time for entries w/o duration information from ytdl
  config/i18n/en.json
  musicbot/bot.py
  musicbot/entry.py
  musicbot/exceptions.py
  musicbot/playlist.py
Labels: a/backend, t/enhancement

#2016 Reuse info_process on searching result
  musicbot/bot.py
Labels: a/backend

#2025 Fix disconnect bug
  musicbot/bot.py
Labels: a/backend
